CREATE TABLE PEDIDO_NOVOS AS SELECT * FROM PEDIDO;
ALTER TABLE PEDIDO_NOVOS ADD STATUS VARCHAR2(30);
SELECT * FROM PEDIDO_NOVOS;

CREATE OR REPLACE TRIGGER TRG_PEDIDO
BEFORE INSERT ON PEDIDO_NOVOS
FOR EACH ROW
BEGIN
IF :NEW.STATUS IS NULL THEN
:NEW.STATUS := 'Novo Pedido';
END IF;
END;

SELECT * FROM PEDIDO_NOVOS;

INSERT INTO pedido_novos (
    cod_pedido,
    cod_cliente
) VALUES ( 1234568,
           10 );
           
SELECT * FROM pedido_novos WHERE cod_pedido = 1234568;
